services:
    saltare.user.provider:
        class: IOKI\SaltareAuthenticationBundle\Security\SaltareUserProvider

    saltare.authentication.provider:
        class:  IOKI\SaltareAuthenticationBundle\Security\SaltareAuthenticationProvider
        arguments: [@saltare.user.provider]

    saltare.authentication.listener:
        class:  IOKI\SaltareAuthenticationBundle\Security\SaltareAuthenticationListener
        arguments: ["@security.context", "@security.authentication.manager"]