security:
    providers:
        custom_authentication.users:
            id: custom_authentication.user.provider

    firewalls:
        custom_authentication:
            pattern: ^/spider/secured
            custom_authentication: true
            security: true
            provider: custom_authentication.users

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
